<?php
require __DIR__ . "/../../vendor/autoload.php";
/** @file
 * @brief Empty unit testing template
 * @cond 
 * @brief Unit tests for the class 
 */
class SteampunkedViewTest extends \PHPUnit_Framework_TestCase
{
	const SEED = 15;

	public function test_construct() {
		$steampunked = new Steampunked\Steampunked(self::SEED);
		$view = new Steampunked\SteampunkedView($steampunked);

        $this->assertInstanceOf('Steampunked\SteampunkedView', $view);
	}

    public function test_smgrid() {
        $steampunked = new Steampunked\Steampunked(self::SEED);
        $view = new Steampunked\SteampunkedView($steampunked);

        $html = '<form method="post" action="">';
        $html .= '<div class="game">';
        $html .='<div class="row">';
        $html .='<div class="cell"><img src="images/valve-closed.png" alt="valve closed"></div>';
        $html .='<div class="cell"><img src="images/straight-h.png" alt="straight h"></div>';
        $html .='<div class="cell"><img src="images/ninety-sw.png" alt="ninety sw"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"><img src="images/gauge-top-0.png" alt="Player 1 top"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"><img src="images/ninety-ne.png" alt="ninety ne"></div>';
        $html .='<div class="cell"><img src="images/straight-h.png" alt="straight h"></div>';
        $html .='<div class="cell"><img src="images/straight-h.png" alt="straight h"></div>';
        $html .='<div class="cell"><img src="images/straight-h.png" alt="straight h"></div>';
        $html .='<div class="cell"><img src="images/straight-h.png" alt="straight h"></div>';
        $html .='<div class="cell"><img src="images/gauge-0.png" alt="Player 1 gauge"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"><img src="images/gauge-top-190.png" alt="Player 2 top"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"><img src="images/gauge-190.png" alt="Player 2 gauge"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"><img src="images/valve-closed.png" alt="valve closed"></div>';
        $html .='<div class="cell"><img src="images/leak-w.png" alt="leak w"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .= '</div>';
        $html .= '</form>';

        $smgrid = $view->displayGridS();
        $this->assertEquals($html, $smgrid);
    }

    public function test_mgrid() {
        $steampunked = new Steampunked\Steampunked(self::SEED);
        $view = new Steampunked\SteampunkedView($steampunked);

        $html = '<form method="post" action="">';
        $html .= '<div class="game">';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .= '</div>';
        $html .= '</form>';

        $mgrid = $view->displayGridM();
        $this->assertEquals($html, $mgrid);
    }

    public function test_lggrid() {
        $steampunked = new Steampunked\Steampunked(self::SEED);
        $view = new Steampunked\SteampunkedView($steampunked);

        $html = '<form method="post" action="">';
        $html .= '<div class="game">';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .='<div class="row">';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='<div class="cell"></div>';
        $html .='</div>';
        $html .= '</div>';
        $html .= '</form>';

        $lggrid = $view->displayGridL();
        $this->assertEquals($html, $lggrid);


    }

    public function test_buttons() {
        $steampunked = new Steampunked\Steampunked(self::SEED);
        $view = new Steampunked\SteampunkedView($steampunked);

        $html = '<form method="post" action="game-post.php">';
        $html .= '<p><label for="piece1"><img src="images/cap-e.png" alt="Piece1"></label><input type="radio" name="piece" id="piece">';
        $html .= '<label for="piece2"><img src="images/straight-h.png" alt="Piece2"></label><input type="radio" name="piece" id="piece">';
        $html .= '<label for="piece3"><img src="images/ninety-wn.png" alt="Piece3"></label><input type="radio" name="piece" id="piece">';
        $html .= '<label for="piece4"><img src="images/tee-nes.png" alt="Piece4"></label><input type="radio" name="piece" id="piece">';
        $html .= '<label for="piece5"><img src="images/straight-v.png" alt="Piece5"></label><input type="radio" name="piece" id="piece"></p>';
        $html .= '<p><input type="submit" name="rotate" value="Rotate">';
        $html .= '<input type="submit" name="discard" value="Discard">';
        $html .= '<input type="submit" name="open" value="Open Valve">';
        $html .= '<input type="submit" name="giveup" value="Give Up"></p>';
        $html .= '</form>';

        $buttons = $view->displayButtons();
        $this->assertEquals($html, $buttons);
    }

    /*
    public function test_turns() {

    }
/* -- these possible go into a different view class, they do not really deal with the game play
    winner may stay though the index could probably be on its own
    public function test_winner() {

    }

    public function test_index() {

    }
*/
}

/// @endcond
?>
